version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions_if_necessary"
    commit_message:
      prefix: "⬆"
