name: Build & Test

on:
  pull_request:
    branches:
      - master
      - alpha

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: npm ci
        run: |
          npm ci
        env:
          CI: true

      - name: npm build & test
        run: |
          npm run build
          npm run test
        env:
          CI: true
